import type { JobId } from '../trace/events'

/**
 * `line` is the 1-based line of the expression that CAUSED the suspend
 * (`delay(100)`, `j.join()`, `d.await()`). The interpreter is the only place
 * that knows it — the scheduler only sees what the generator yielded.
 * Optional because `joinChildren` is generated by the builder, not by any
 * single line of user code.
 */
export type Suspension =
  | { s: 'delay'; ms: number; line?: number }
  | { s: 'join'; jobId: JobId; line?: number }
  | { s: 'await'; jobId: JobId; line?: number }
  /** Wait for EVERY child of jobId to finish. coroutineScope/supervisorScope use this. */
  | { s: 'joinChildren'; jobId: JobId; line?: number }
  | { s: 'yield'; line?: number }
  /**
   * Switch dispatcher mid-flight (withContext). The task is re-queued onto
   * the new pool's ready queue: the old thread was released at the end of
   * step(), the new thread gets acquired on the next step — that's the
   * entire "thread switch" mechanism the learner sees.
   *
   * `jobId` is the job that gets named in the DISPATCH event: the
   * withContext job on the way OUT (it's the one being dispatched to the new
   * dispatcher), the calling job on the way BACK (by then the withContext
   * job has Completed and can no longer be dispatched anywhere).
   */
  | { s: 'switchContext'; jobId: JobId; dispatcher: string; line?: number }

/**
 * The coroutine body: a generator that yields at suspend points and
 * receives the resume value back.
 *
 * The RETURN value is `unknown`, not `void`: an `async` body must be able to
 * carry its result out for `Deferred.await()` to read. With `void` the
 * scheduler would have nothing to store, and await would have no choice but
 * to return Unit — exactly the silent bug that Task 3 fixed.
 */
export type CoroutineBody = Generator<Suspension, unknown, unknown>

/**
 * A coroutine body that does NOT carry a value out — every builder except
 * `async`, plus hand-built bodies in tests.
 *
 * Exists only because TypeScript requires a function declared to return
 * `unknown` to have an explicit `return`; writing `return undefined` at the
 * end of a few dozen generators that return nothing anyway is noise, not
 * information. Assignment-wise it's still a valid `CoroutineBody`, so the
 * scheduler doesn't need to know about it.
 */
export type VoidCoroutineBody = Generator<Suspension, void, unknown>
